### ISSUE TITLE
Support passing whole model to usePost

### ISSUE THREAD

**Issue by renatoruk** [bornfight/aardvark#24]

**Comment by renatoruk** [comment]
> I think this is done, we have usePatch and usePost which both accept "rawData" attribute or in another words, support passing a whole model. And customly written at that. Is it not?

@JuraJuki this is relevant to https://github.com/bornfight/aardvark/issues/43 that's still opened. It might be a duplicate, tho. Shall we close this one?

**Comment by JuraJuki** [comment]
I agree. Closing
